name: Version @coinbase/cdp-sdk

on:
  workflow_dispatch:

jobs:
  version:
    name: Version
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          version: 10

      - name: Setup Node
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"
          cache-dependency-path: ./typescript

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ./typescript

      - name: Version
        uses: changesets/action@06245a4e0a36c064a573d4150030f5ec548e4fcc # v1.4.10
        with:
          commit: "chore: version @coinbase/cdp-sdk"
          title: "chore: version @coinbase/cdp-sdk"
          version: pnpm run changeset:version
          cwd: ./typescript
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
